param(
    [string]$OutputRoot = "$PSScriptRoot\..\references\typeui-registry"
)

$ErrorActionPreference = "Stop"

$indexUrl = "https://raw.githubusercontent.com/bergside/awesome-design-skills/main/skills/index.json"
$outputRootResolved = (Resolve-Path $OutputRoot).Path
$skillsDir = Join-Path $outputRootResolved "skills"
$catalogJsonPath = Join-Path $outputRootResolved "catalog.json"
$catalogMdPath = Join-Path $outputRootResolved "catalog.md"
$sourceIndexPath = Join-Path $outputRootResolved "source-index.json"

New-Item -ItemType Directory -Force $skillsDir | Out-Null

$index = Invoke-RestMethod -Uri $indexUrl
$entries = @()

foreach ($property in $index.PSObject.Properties) {
    $entry = $property.Value
    $slug = $entry.slug
    $name = $entry.name
    $skillPath = $entry.skillPath
    $rawUrl = "https://raw.githubusercontent.com/bergside/awesome-design-skills/main/$skillPath"
    $targetPath = Join-Path $skillsDir "$slug.md"

    $markdown = (Invoke-WebRequest -Uri $rawUrl).Content
    Set-Content -LiteralPath $targetPath -Value $markdown -Encoding UTF8

    $description = ""
    foreach ($line in ($markdown -split "`r?`n")) {
        if ($line -like "description:*") {
            $description = $line.Substring("description:".Length).Trim().Trim('"')
            break
        }
    }

    $entries += [pscustomobject]@{
        slug = $slug
        name = $name
        description = $description
        source = $rawUrl
        localFile = "skills/$slug.md"
    }
}

$sortedEntries = $entries | Sort-Object slug
$sortedEntries | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $catalogJsonPath -Encoding UTF8
($index | ConvertTo-Json -Depth 6) | Set-Content -LiteralPath $sourceIndexPath -Encoding UTF8

$lines = @(
    "# TypeUI Registry Catalog",
    "",
    "Generated by `scripts/sync-typeui-registry.ps1` from the public TypeUI registry.",
    "",
    "Read this file first, then open only the template files you need from `skills/*.md`.",
    "",
    "| Slug | Name | Summary |",
    "| --- | --- | --- |"
)

foreach ($entry in $sortedEntries) {
    $summary = if ($entry.description) { $entry.description } else { "No description parsed." }
    $safeSummary = $summary.Replace("|", "\|")
    $lines += "| $($entry.slug) | $($entry.name) | $safeSummary |"
}

$lines += ""
$lines += "Total templates: $($sortedEntries.Count)"
$lines += ""
$lines += "When the user asks for options, use `page-type-variants.md` to narrow to a few strong anchors before reading full template files."

Set-Content -LiteralPath $catalogMdPath -Value ($lines -join "`r`n") -Encoding UTF8
